
# Site settings

url: "https://banjerr.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl:

google-tracking-id: "UA-69517842-1"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Ben Redden"
lang: "en"
title: "{ Banjerr }"
favicon: "/img/favicon.ico"
description: "Cyber, transcendental home of Banjerr (Ben Redden). Father, web developer, old time music enthusiast, banjo builder, dreamer"
keywords: "redden, ben, banjo, developer, php, wordpress, jquery, javascript, html, css"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "/img/intro-bg.jpg"
me-img: "/img/banjerr.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

########
# Blog #
########

post-preview-words: 46

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: ""

###############
# Life Events #
###############

events:
  - image: "/img/career/getuwired.png"
    date: "April 21 2014 - present"
    description: "Started working as a web developer at one of the coolest places possible, GetUWired"
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the world!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2013 - present"
    description: "Started coding (seriously, not just Angelfire and Tripod pages =P)"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "admin@benjaminredden.we.bs"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/benjamminredden"
  - title: "twitter"
    url: "https://twitter.com/_bengineer_"
  - title: "youtube"
    url: "https://youtube.com/blueholygrass"
  - title: "github"
    url: "https://github.com/Banjerr"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"
gems: [jekyll-paginate]

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
